"""Copy the local Docker corpus into Supabase, preserving primary keys.

The demo data CANNOT be regenerated by re-running the pipeline against a fresh
database. ``scripts/seed_demo_attributes.py`` and ``scripts/jerusalem_geocode_recovery.py``
both address rows by hard-coded UUIDs, while ``app.ingestion.seed_import`` lets
PostgreSQL mint ids from ``gen_random_uuid()``. A fresh import therefore produces
different ids, and both demo scripts would then match zero rows — losing exactly the
MATCH / NO_MATCH cases the run-sheet walks through. Copying the rows verbatim is the
only route that keeps those verdicts intact, and it also carries ``geocode_cache``
across, so no Google query is ever re-billed.

Mechanics: ``pg_dump --data-only`` one table at a time, in foreign-key dependency
order taken from ``Base.metadata.sorted_tables``. A single whole-database
``--data-only`` dump is NOT safe here — pg_dump does not order data for foreign keys,
and restoring it would fail partway through. Both ``pg_dump`` and ``psql`` are run
inside the ``db`` container, which has them at the matching server version; neither
needs to be on the host PATH.

    python scripts/copy_to_supabase.py              # dry run: compares both sides
    python scripts/copy_to_supabase.py --apply      # copy
    python scripts/copy_to_supabase.py --apply --force   # allow a non-empty target

The target is required to be empty unless ``--force`` is passed, because every table
here would otherwise take a second copy of every row.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy import URL, create_engine, text  # noqa: E402

import app.models  # noqa: E402, F401  registers every table on Base.metadata
from app.core.config import settings  # noqa: E402
from app.db.base import Base  # noqa: E402
from app.db.connection import build_connect_args, normalized_url  # noqa: E402

#: Docker Desktop does not put docker.exe on PATH on this machine (see run-demo.ps1).
DOCKER_FALLBACK_PATH = r"C:\Program Files\Docker\Docker\resources\bin\docker.exe"
DOCKER_EXECUTABLE = "docker"

COMPOSE_DB_SERVICE = "db"
LOCAL_DB_USER = "kashroot"
LOCAL_DB_PASSWORD = "kashroot"
LOCAL_DB_NAME = "kashroot"
#: docker-compose publishes the container's 5432 here; a native Windows PostgreSQL
#: service already owns 5432 on this machine (see run-demo.ps1).
LOCAL_DB_PORT = 5433
LOCAL_DB_HOST = "localhost"

PG_PASSWORD_ENV = "PGPASSWORD"
PSQL_STOP_ON_ERROR = ["-v", "ON_ERROR_STOP=1"]
PSQL_SINGLE_TRANSACTION = "--single-transaction"

ALEMBIC_REVISION_QUERY = "SELECT version_num FROM alembic_version"
IDENTITY_COLUMNS_QUERY = """
SELECT table_name, column_name
FROM information_schema.columns
WHERE table_schema = 'public' AND is_identity = 'YES'
"""
SETVAL_TEMPLATE = (
    "SELECT setval(pg_get_serial_sequence('{table}', '{column}'), "
    "COALESCE((SELECT MAX({column}) FROM {table}), 1), true)"
)

CONNECT_TIMEOUT_SECONDS = 15
DUMP_TIMEOUT_SECONDS = 600
RESTORE_TIMEOUT_SECONDS = 1800

DOCKER_MISSING_ERROR = (
    "docker not found on PATH or at {path}. Start Docker Desktop and wait for "
    "'Engine running', then re-run."
)
SOURCE_UNREACHABLE_ERROR = (
    "Local database unreachable at {host}:{port} — run `docker compose up -d db` first."
)
TARGET_UNREACHABLE_ERROR = "Supabase unreachable at {host}: {error}"
REVISION_MISMATCH_ERROR = (
    "Schema mismatch: local is at Alembic revision {source!r} but Supabase is at "
    "{target!r}. Bring them to the same revision before copying data."
)
TARGET_NOT_EMPTY_ERROR = (
    "Supabase already holds rows ({summary}). Copying now would duplicate them. "
    "Empty those tables first, or pass --force if you are certain."
)
DUMP_FAILED_ERROR = "pg_dump failed for table {table!r}: {stderr}"
RESTORE_FAILED_ERROR = "psql restore failed: {stderr}"
COUNT_MISMATCH_ERROR = "Row counts differ after copy — {table}: local {source}, supabase {target}"


def resolve_docker() -> str:
    """
    Locate the docker executable.

    Return:
        str: Path to docker, preferring PATH and falling back to the Docker Desktop
            install location.
    """
    found = shutil.which(DOCKER_EXECUTABLE)
    if found:
        return found

    if Path(DOCKER_FALLBACK_PATH).exists():
        return DOCKER_FALLBACK_PATH

    raise SystemExit(DOCKER_MISSING_ERROR.format(path=DOCKER_FALLBACK_PATH))


def ordered_tables() -> list[str]:
    """
    Table names in foreign-key dependency order.

    SQLAlchemy already computes this topological sort for ``create_all``; reusing it
    means the copy order can never drift from the schema.

    Return:
        list[str]: Parent tables before the tables that reference them.
    """
    return [table.name for table in Base.metadata.sorted_tables]


def local_url() -> URL:
    """
    URL of the local Docker Postgres, independent of what .env currently points at.

    Return:
        URL: SQLAlchemy URL for the compose database on its published port.
    """
    return URL.create(
        drivername="postgresql+psycopg",
        username=LOCAL_DB_USER,
        password=LOCAL_DB_PASSWORD,
        host=LOCAL_DB_HOST,
        port=LOCAL_DB_PORT,
        database=LOCAL_DB_NAME,
    )


def connect(url: URL, *, connect_args: dict | None = None):
    """
    Open a short-lived engine against a database.

    Parameters:
        url (URL): Target database URL.
        connect_args (dict | None): Extra DBAPI connect arguments.

    Return:
        Engine: A disposable SQLAlchemy engine.
    """
    args = {"connect_timeout": CONNECT_TIMEOUT_SECONDS}
    args.update(connect_args or {})

    return create_engine(url, pool_pre_ping=True, connect_args=args)


def revision_of(url: URL, *, connect_args: dict | None = None) -> str | None:
    """
    Alembic revision a database is at.

    Parameters:
        url (URL): Target database URL.
        connect_args (dict | None): Extra DBAPI connect arguments.

    Return:
        str | None: The revision, or None when the table is absent or empty.
    """
    engine = connect(url, connect_args=connect_args)
    try:
        with engine.connect() as connection:
            return connection.execute(text(ALEMBIC_REVISION_QUERY)).scalar_one_or_none()
    finally:
        engine.dispose()


def counts_of(url: URL, tables: list[str], *, connect_args: dict | None = None) -> dict[str, int]:
    """
    Row count per table.

    Parameters:
        url (URL): Target database URL.
        tables (list[str]): Tables to count.
        connect_args (dict | None): Extra DBAPI connect arguments.

    Return:
        dict[str, int]: Table name to row count.
    """
    engine = connect(url, connect_args=connect_args)
    counts: dict[str, int] = {}
    try:
        with engine.connect() as connection:
            for table in tables:
                counts[table] = connection.execute(
                    text(f"SELECT count(*) FROM {table}")
                ).scalar_one()
    finally:
        engine.dispose()

    return counts


def dump_table(docker: str, table: str) -> bytes:
    """
    Dump one table's rows from the compose database as SQL.

    Parameters:
        docker (str): Path to the docker executable.
        table (str): Table to dump.

    Return:
        bytes: SQL text, UTF-8, as pg_dump produced it.
    """
    result = subprocess.run(
        [
            docker,
            "compose",
            "exec",
            "-T",
            COMPOSE_DB_SERVICE,
            "pg_dump",
            "-U",
            LOCAL_DB_USER,
            "-d",
            LOCAL_DB_NAME,
            "--data-only",
            "--no-owner",
            "--table",
            table,
        ],
        capture_output=True,
        timeout=DUMP_TIMEOUT_SECONDS,
        check=False,
    )
    if result.returncode != 0:
        raise SystemExit(
            DUMP_FAILED_ERROR.format(table=table, stderr=result.stderr.decode(errors="replace"))
        )

    return result.stdout


def restore(docker: str, sql: bytes, target: URL) -> None:
    """
    Feed dumped SQL into the Supabase database through the container's psql.

    The password travels as an environment variable rather than inside the connection
    string, so it never appears in the container's process arguments.

    Parameters:
        docker (str): Path to the docker executable.
        sql (bytes): Concatenated dump, already in dependency order.
        target (URL): Supabase database URL.

    Return:
        None
    """
    result = subprocess.run(
        [
            docker,
            "compose",
            "exec",
            "-T",
            "-e",
            f"{PG_PASSWORD_ENV}={target.password}",
            COMPOSE_DB_SERVICE,
            "psql",
            PSQL_SINGLE_TRANSACTION,
            *PSQL_STOP_ON_ERROR,
            "-h",
            str(target.host),
            "-p",
            str(target.port),
            "-U",
            str(target.username),
            "-d",
            str(target.database),
        ],
        input=sql,
        capture_output=True,
        timeout=RESTORE_TIMEOUT_SECONDS,
        check=False,
    )
    if result.returncode != 0:
        raise SystemExit(RESTORE_FAILED_ERROR.format(stderr=result.stderr.decode(errors="replace")))


def reset_identity_sequences(url: URL, *, connect_args: dict | None = None) -> list[str]:
    """
    Advance identity sequences past the copied rows.

    Explicit values inserted into a ``GENERATED BY DEFAULT AS IDENTITY`` column (here,
    ``audit_log.seq``) do not move the underlying sequence, so the next insert would
    collide. Discovered from the catalog rather than hard-coded, so a future identity
    column is handled without editing this script.

    Parameters:
        url (URL): Target database URL.
        connect_args (dict | None): Extra DBAPI connect arguments.

    Return:
        list[str]: The ``table.column`` pairs that were advanced.
    """
    engine = connect(url, connect_args=connect_args)
    advanced: list[str] = []
    try:
        with engine.begin() as connection:
            rows = connection.execute(text(IDENTITY_COLUMNS_QUERY)).all()
            for table, column in rows:
                connection.execute(text(SETVAL_TEMPLATE.format(table=table, column=column)))
                advanced.append(f"{table}.{column}")
    finally:
        engine.dispose()

    return advanced


def main() -> None:
    """
    Compare both databases and, with --apply, copy local rows into Supabase.

    Return:
        None
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true", help="Copy. Without it, only report.")
    parser.add_argument("--force", action="store_true", help="Allow a non-empty target.")
    args = parser.parse_args()

    docker = resolve_docker()
    tables = ordered_tables()
    source = local_url()
    target = normalized_url(settings.database_url)
    target_connect_args = build_connect_args(settings.database_url)

    try:
        source_counts = counts_of(source, tables)
    except Exception as exc:
        raise SystemExit(
            SOURCE_UNREACHABLE_ERROR.format(host=source.host, port=source.port)
        ) from exc

    try:
        target_counts = counts_of(target, tables, connect_args=target_connect_args)
    except Exception as exc:
        raise SystemExit(TARGET_UNREACHABLE_ERROR.format(host=target.host, error=exc)) from exc

    source_revision = revision_of(source)
    target_revision = revision_of(target, connect_args=target_connect_args)
    if source_revision != target_revision:
        raise SystemExit(
            REVISION_MISMATCH_ERROR.format(source=source_revision, target=target_revision)
        )

    print(f"\ncopy-to-supabase — {target.host}")
    print(f"  alembic revision       {source_revision}")
    print(f"  {'table':<30} {'local':>8} {'supabase':>10}")
    for table in tables:
        print(f"  {table:<30} {source_counts[table]:>8} {target_counts[table]:>10}")

    occupied = {t: n for t, n in target_counts.items() if n}
    if occupied and not args.force:
        summary = ", ".join(f"{t}={n}" for t, n in occupied.items())
        raise SystemExit(f"\n{TARGET_NOT_EMPTY_ERROR.format(summary=summary)}")

    if not args.apply:
        total = sum(source_counts.values())
        print(f"\n  DRY RUN — {total} rows would be copied. Re-run with --apply.")

        return

    print("\n  dumping (foreign-key order)")
    chunks: list[bytes] = []
    for table in tables:
        chunk = dump_table(docker, table)
        chunks.append(chunk)
        print(f"    {table:<30} {len(chunk):>10} bytes")

    print("\n  restoring into Supabase (single transaction)")
    restore(docker, b"\n".join(chunks), target)

    advanced = reset_identity_sequences(target, connect_args=target_connect_args)
    for name in advanced:
        print(f"    identity sequence advanced: {name}")

    print("\n  verifying")
    final_counts = counts_of(target, tables, connect_args=target_connect_args)
    mismatches = [t for t in tables if final_counts[t] != source_counts[t]]
    for table in tables:
        mark = "MISMATCH" if table in mismatches else "ok"
        print(f"    {table:<30} {final_counts[table]:>8}  {mark}")

    if mismatches:
        table = mismatches[0]
        raise SystemExit(
            COUNT_MISMATCH_ERROR.format(
                table=table, source=source_counts[table], target=final_counts[table]
            )
        )

    print(f"\n  COPIED — {sum(final_counts.values())} rows, ids preserved.")
    print("  Next: kashroot db-check, then kashroot storage-check --create-bucket")


if __name__ == "__main__":
    main()
